apiVersion: v1
kind: Secret
metadata:
  name: awsiot-connector-config
type: Opaque
stringData:
  aws-iot-mqtt-connector.json: |-
    {
      "name" : "AWSIoTSourceConnector",
      "config" : {
        "connector.class" : "io.confluent.connect.mqtt.MqttSourceConnector",
        "confluent.topic.bootstrap.servers" : "[CCLOUD_BOOTSTRAP]",
        "confluent.topic.ssl.endpoint.identification.algorithm" : "https",
        "confluent.topic.sasl.mechanism" : "PLAIN",
        "confluent.topic.sasl.jaas.config" : "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"[CCLOUD_KEY]\" password=\"[CCLOUD_SECRET]\";",
        "confluent.topic.security.protocol" : "SASL_SSL",    
        "value.converter" : "org.apache.kafka.connect.converters.ByteArrayConverter",
        "tasks.max" : "1",
        "mqtt.server.uri" : "[AWS_IOT_SERVER_URI]",
        "mqtt.topics" : "sdk/test/java",
        "mqtt.ssl.trust.store.path" : "/mnt/secrets/awsiot-truststore.jks",
        "mqtt.ssl.trust.store.password" : "[TRUSTSTORE_PWD]",
        "mqtt.ssl.key.store.path": "/mnt/secrets/awsiot-keystore.jks",
        "mqtt.ssl.key.store.password" : "[KEYSTORE_PWD]",
        "mqtt.ssl.key.password" : "[KEYSTORE_PWD]"
      }
    }
