apiVersion: v1
kind: Secret
metadata:
  {{- include "confluent-operator.labels" . }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-apikeys
type: Opaque
data:
  apikeys.json : {{ include "confluent-operator.apikeys" . | b64enc }}
  jksPassword.txt: {{ (printf "jksPassword=%s" .Values.tls.jksPassword) | b64enc }}
  {{- include "confluent-operator.mds-credential-secret" . | indent 2 }}
  ###
  # CHANGE HERE
  # Add next 2 lines with the base64 encoded content
  # of your truststore and keystore
  # required to access your AWS IoT Service
  ###
  awsiot-keystore.jks: [BASE64_AWS_IOT_KEYSTORE]
  awsiot-truststore.jks: [BASE64_AWS_IOT_TRUSTSTORE]

